"""Proactive insights API endpoint."""
from fastapi import APIRouter
from typing import List
from opera.backend.services.background_reasoner import get_background_reasoner, Insight

router = APIRouter(prefix="/insights", tags=["insights"])


@router.get("/", response_model=List[dict])
async def get_insights(limit: int = 10):
    """
    Get recent proactive insights generated by background analysis.
    
    Returns insights about patterns, goals, connections, and suggestions.
    """
    reasoner = get_background_reasoner()
    insights = reasoner.get_insights(limit=limit)
    return insights


@router.post("/analyze")
async def trigger_analysis():
    """
    Manually trigger background analysis.
    
    Useful for testing or forcing immediate insight generation.
    """
    reasoner = get_background_reasoner()
    insights = await reasoner.analyze()
    
    return {
        "status": "analysis_complete",
        "insights_generated": len(insights),
        "insights": insights
    }
